spring:
  application:
    name: bookmanager

  datasource:
    url: jdbc:mysql://mysql:3306/bookdb?useSSL=false&serverTimezone=Asia/Taipei&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      initialization-fail-timeout: -1  # 不因失败而停止启动

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always

jwt:
  secret: w8Qw1QkQw2Qw3Qw4Qw5Qw6Qw7Qw8Qw9Qw0Qw1Qw2Qw3Qw4Qw5Qw6Qw7Qw8Qw9Qw0Qw1Qw2Qw3Qw4Qw5Qw6Qw7Qw8Qw9Qw0Q==
  expirationMs: 3600000 # 1 小时
